language: go

go:
  - "1.12"

env:
  - GO111MODULE=on

install:
  - go mod download
  - go get -t golang.org/x/tools/cmd/cover
  - go get -t github.com/mattn/goveralls

script:
  - make coverage
  - $HOME/gopath/bin/goveralls -coverprofile=artifacts/c.out -service=travis-pro -repotoken=$COVERALLS_TOKEN
