name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit_tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        go: ['1.15', '1.16', '1.17']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Test using Make
        run: make test
