name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit_tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        go: ['1.15', '1.16', '1.17']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Get coverage tools
        run: |
          go get github.com/ory/go-acc
          go get golang.org/x/tools/cmd/cover

      - name: Run tests, generate coverage
        run: make coverage

      - name: Install goveralls
        if: matrix.go == '1.15'
        run: go install github.com/mattn/goveralls

      - name: Install goveralls
        if: matrix.go != '1.15'
        run: go install github.com/mattn/goveralls@latest

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=artifacts/c.out -service=github
