name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test using Make
      run: make test
